---
- name: Mostrar información del sistema
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - block:
        - name: Imprimir la distribución de Linux
          ansible.builtin.debug:
            msg: "La distribución de Linux es: {{ ansible_distribution }}"

        - name: Imprimir el directorio donde se ejecuta el playbook
          ansible.builtin.debug:
            msg: "El playbook se ejecuta en el directorio: {{ playbook_dir }}"

        - name: Imprimir el nombre del play que se está ejecutando
          ansible.builtin.debug:
            msg: "El nombre del play es: {{ ansible_play_name }}"
            
      name: Información del sistema y entorno de ejecución
    - block:
        - name: Numero de CPUs
          ansible.builtin.debug:
            msg: "Número de procesadores: {{ ansible_processor_vcpus }}"

        - name: Memoria RAM total en MB
          ansible.builtin.debug:
            msg: "Memoria RAM total: {{ ansible_memtotal_mb }} MB"

        - name: Arquitectura del sistema
          ansible.builtin.debug:
            msg: "Arquitectura: {{ ansible_architecture }}"
            
      name: Información más avanzada del sistema
